---
language: go

before_install:
  - sudo apt-get update -qq > apt-get.out || (cat apt-get.out && exit 1)
  - sudo apt-get install bzr mercurial git libyaml-dev cmake -qq >> apt-get.out || (cat apt-get.out && exit 1)

services:
  - redis-server

install:
  - mv $GOPATH/src/github.com/fd/simplex $GOPATH/src/simplex.sh
  - make -C $GOPATH/src/simplex.sh

script:
  - make -C $GOPATH/src/simplex.sh test
