#!/bin/sh

x() {
	echo '--- ' "$@"
	"$@"
	echo '---'
	echo
}

x sx help
x sx help build
x sx help clean
x sx help install
x sx help fix
x sx help fmt
x sx help get
x sx help list
x sx help test
x sx help version
x sx help vet
x sx help gopath
x sx help importpath
x sx help remote
